#!/usr/bin/env bash
# =============================================================================
# Codika WhatsApp Connector - One-Command Setup
# =============================================================================
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()    { echo -e "${BLUE}>>>${NC} $1"; }
success() { echo -e "${GREEN}>>>${NC} $1"; }
warn()    { echo -e "${YELLOW}>>>${NC} $1"; }
fail()    { echo -e "${RED}>>>${NC} $1"; exit 1; }

INSTANCE_NAME="bot"

echo ""
echo -e "${BOLD}  Codika WhatsApp Connector Setup${NC}"
echo "  ================================="
echo ""

# ---- 1. Check Docker ----
if ! command -v docker &> /dev/null; then
    info "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    success "Docker installed"
fi

if ! docker compose version &> /dev/null 2>&1; then
    fail "Docker Compose V2 not found. Update Docker: https://docs.docker.com/compose/install/"
fi

success "Docker ready"

# ---- 2. Check if already configured ----
if [ -f .env ]; then
    warn "Already configured."
    read -p "  Restart with existing config? (Y/n): " restart_choice
    if [[ "$restart_choice" =~ ^[Nn]$ ]]; then
        info "To reconfigure from scratch: rm .env && ./setup.sh"
        exit 0
    fi
    docker compose up -d
    EVO_API_KEY=$(grep EVOLUTION_API_KEY .env | cut -d= -f2)
    SERVER_IP=$(grep EVOLUTION_SERVER_URL .env | sed 's|.*//||' | sed 's|:.*||')
    echo ""
    success "Services running!"
    echo ""
    echo -e "  ${BOLD}Management page:${NC}  http://${SERVER_IP}:3000#key=${EVO_API_KEY}"
    echo ""
    exit 0
fi

# ---- 3. Collect the TWO things we need ----
echo -e "  You need ${BOLD}two things${NC} from your Codika dashboard:"
echo ""
echo -e "  ${DIM}1. Webhook URL  - the endpoint where messages are forwarded"
echo -e "  2. API Key     - authenticates requests to Codika${NC}"
echo ""

read -p "  Webhook URL: " CODIKA_WEBHOOK_URL
if [ -z "$CODIKA_WEBHOOK_URL" ]; then
    fail "Webhook URL is required. Find it in your Codika dashboard."
fi

read -p "  API Key: " CODIKA_API_KEY
if [ -z "$CODIKA_API_KEY" ]; then
    fail "API Key is required. Find it in your Codika dashboard."
fi

# ---- 4. Auto-detect everything else ----
info "Detecting server IP..."

SERVER_IP=$(curl -s --max-time 5 https://ifconfig.me 2>/dev/null \
         || curl -s --max-time 5 https://api.ipify.org 2>/dev/null \
         || curl -s --max-time 5 https://icanhazip.com 2>/dev/null \
         || hostname -I 2>/dev/null | awk '{print $1}' \
         || echo "localhost")

success "Server IP: ${SERVER_IP}"

# Generate internal secrets automatically
EVO_API_KEY=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 16)

# ---- 5. Write .env ----
cat > .env << EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# To reconfigure: rm .env && ./setup.sh

# Codika connection (provided by user)
CODIKA_WEBHOOK_URL=${CODIKA_WEBHOOK_URL}
CODIKA_API_KEY=${CODIKA_API_KEY}

# Internal secrets (auto-generated)
EVOLUTION_API_KEY=${EVO_API_KEY}
EVOLUTION_API_VERSION=v2.3.7
EVOLUTION_API_PORT=8080
EVOLUTION_SERVER_URL=http://${SERVER_IP}:8080
SETUP_UI_PORT=3000
POSTGRES_DB=evolution_db
POSTGRES_USER=evolution
POSTGRES_PASSWORD=${DB_PASSWORD}
SESSION_PHONE_CLIENT=Community Bot
DEL_INSTANCE=false
EOF

success "Configuration generated"

# ---- 6. Start services ----
info "Starting services (first run downloads images, may take a few minutes)..."
docker compose up -d

info "Waiting for Evolution API to be ready..."
attempts=0
until docker exec evolution_api wget --spider -q http://localhost:8080 2>/dev/null; do
    attempts=$((attempts + 1))
    if [ $attempts -ge 60 ]; then
        fail "Services did not start. Run: docker compose logs evolution-api"
    fi
    sleep 2
done

success "Evolution API is running"

# ---- 7. Create instance with per-instance webhook ----
info "Creating WhatsApp instance with webhook forwarding..."

# Build webhook URL with API key as query parameter (reliable fallback)
# Also set headers for X-API-Key (works in v2.3.7+ per-instance webhooks)
# The n8n receiver should check both header and query param
if [[ "${CODIKA_WEBHOOK_URL}" == *"?"* ]]; then
    WEBHOOK_URL_WITH_KEY="${CODIKA_WEBHOOK_URL}&apiKey=${CODIKA_API_KEY}"
else
    WEBHOOK_URL_WITH_KEY="${CODIKA_WEBHOOK_URL}?apiKey=${CODIKA_API_KEY}"
fi

WEBHOOK_EVENTS='["MESSAGES_UPSERT","MESSAGES_UPDATE","CONNECTION_UPDATE","QRCODE_UPDATED","GROUPS_UPSERT","GROUPS_UPDATE","GROUP_PARTICIPANTS_UPDATE"]'

# Create instance with per-instance webhook configuration
HTTP_STATUS=$(curl -s -o /tmp/evo_create_response.json -w "%{http_code}" \
    -X POST "http://localhost:8080/instance/create" \
    -H "apikey: ${EVO_API_KEY}" \
    -H "Content-Type: application/json" \
    -d "{
        \"instanceName\": \"${INSTANCE_NAME}\",
        \"integration\": \"WHATSAPP-BAILEYS\",
        \"qrcode\": true,
        \"webhook\": {
            \"url\": \"${WEBHOOK_URL_WITH_KEY}\",
            \"headers\": {
                \"X-API-Key\": \"${CODIKA_API_KEY}\"
            },
            \"byEvents\": false,
            \"base64\": false,
            \"events\": ${WEBHOOK_EVENTS}
        }
    }")

if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
    success "WhatsApp instance created"
elif [ "$HTTP_STATUS" -eq 403 ] || [ "$HTTP_STATUS" -eq 409 ]; then
    # Instance already exists -- update its webhook config
    warn "Instance already exists, updating webhook configuration..."
    curl -s -o /dev/null \
        -X POST "http://localhost:8080/webhook/set/${INSTANCE_NAME}" \
        -H "apikey: ${EVO_API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{
            \"enabled\": true,
            \"url\": \"${WEBHOOK_URL_WITH_KEY}\",
            \"headers\": {
                \"X-API-Key\": \"${CODIKA_API_KEY}\"
            },
            \"webhookByEvents\": false,
            \"webhookBase64\": false,
            \"events\": ${WEBHOOK_EVENTS}
        }"
    success "Webhook configuration updated"
else
    warn "Instance creation returned HTTP ${HTTP_STATUS}. You may need to create it manually via the management page."
    cat /tmp/evo_create_response.json 2>/dev/null || true
fi

rm -f /tmp/evo_create_response.json

# ---- 8. Done! ----
echo ""
echo -e "${GREEN}  ==========================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}  ==========================================${NC}"
echo ""
echo -e "  ${BOLD}Open this URL in your browser to scan the QR code:${NC}"
echo ""
echo -e "  ${BLUE}http://${SERVER_IP}:3000#key=${EVO_API_KEY}${NC}"
echo ""
echo "  Steps:"
echo "  1. Open the URL above in your browser"
echo "  2. Click 'Connect' (or the instance will be ready for QR)"
echo "  3. Open WhatsApp on your phone"
echo "  4. Go to Settings > Linked Devices > Link a Device"
echo "  5. Scan the QR code shown on the page"
echo ""
echo -e "  ${YELLOW}Bookmark the URL above - it's your management page.${NC}"
echo ""
