#!/usr/bin/env bash
# =============================================================================
# Codika Baileys Connector - Setup Script
# =============================================================================
# This script configures and starts the WhatsApp connector.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo "==========================================="
echo "  Codika WhatsApp Connector Setup"
echo "==========================================="
echo ""

# ---- Check Docker ----
if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker first:\n  https://docs.docker.com/engine/install/"
fi

if ! docker compose version &> /dev/null 2>&1; then
    error "Docker Compose V2 is not available. Please update Docker:\n  https://docs.docker.com/compose/install/"
fi

success "Docker and Docker Compose detected"

# ---- Check if already configured ----
if [ -f .env ]; then
    warn ".env file already exists."
    read -p "Overwrite with fresh configuration? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        info "Keeping existing .env. Starting services..."
        docker compose up -d
        echo ""
        success "Services started! API available at: $(grep EVOLUTION_SERVER_URL .env | cut -d= -f2)"
        exit 0
    fi
fi

# ---- Collect configuration ----
echo ""
info "Let's configure your connector. You'll need:"
echo "  1. Your Codika webhook URL (from your dashboard)"
echo "  2. Your server's public IP or domain"
echo ""

# Webhook URL
read -p "Codika webhook URL: " webhook_url
if [ -z "$webhook_url" ]; then
    error "Webhook URL is required."
fi

# Server URL
default_port=8080
read -p "Server public IP or domain (e.g. 123.45.67.89 or connector.example.com): " server_host
if [ -z "$server_host" ]; then
    error "Server address is required."
fi

# Detect if domain or IP
if [[ "$server_host" == *"."* ]] && ! [[ "$server_host" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    # It's a domain - assume HTTPS
    server_url="https://${server_host}"
    info "Domain detected - using HTTPS. Make sure you have a reverse proxy (nginx/caddy) with SSL configured."
else
    # It's an IP - use HTTP with port
    read -p "Port (default: ${default_port}): " port
    port=${port:-$default_port}
    server_url="http://${server_host}:${port}"
fi

# Device name
read -p "Bot name (shown on phone's linked devices, default: Community Bot): " bot_name
bot_name=${bot_name:-Community Bot}

# Generate secrets
api_key=$(openssl rand -hex 32)
db_password=$(openssl rand -hex 16)

# ---- Write .env ----
cat > .env << EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Codika webhook URL
WEBHOOK_URL=${webhook_url}
WEBHOOK_ENABLED=true

# Evolution API
EVOLUTION_API_KEY=${api_key}
EVOLUTION_API_VERSION=v2.3.7
EVOLUTION_API_PORT=${port:-$default_port}
EVOLUTION_SERVER_URL=${server_url}

# PostgreSQL
POSTGRES_DB=evolution_db
POSTGRES_USER=evolution
POSTGRES_PASSWORD=${db_password}

# Session
SESSION_PHONE_CLIENT=${bot_name}
DEL_INSTANCE=false
EOF

success ".env file created"
echo ""

# ---- Start services ----
info "Starting services..."
docker compose up -d

echo ""
info "Waiting for Evolution API to be ready..."
attempts=0
max_attempts=30
until docker exec evolution_api wget --spider -q http://localhost:8080 2>/dev/null; do
    attempts=$((attempts + 1))
    if [ $attempts -ge $max_attempts ]; then
        error "Evolution API did not start within 60 seconds. Check logs: docker compose logs evolution-api"
    fi
    sleep 2
done

echo ""
echo "==========================================="
success "Setup complete!"
echo "==========================================="
echo ""
echo "  API URL:     ${server_url}"
echo "  API Key:     ${api_key}"
echo ""
echo "  Next steps:"
echo "  1. Create a WhatsApp instance:"
echo ""
echo "     curl -X POST ${server_url}/instance/create \\"
echo "       -H 'apikey: ${api_key}' \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"instanceName\": \"bot\", \"integration\": \"WHATSAPP-BAILEYS\"}'"
echo ""
echo "  2. Get the QR code to link your phone:"
echo ""
echo "     curl ${server_url}/instance/connect/bot \\"
echo "       -H 'apikey: ${api_key}'"
echo ""
echo "  3. Open WhatsApp on your phone > Settings > Linked Devices > Link a Device"
echo "     Scan the QR code from step 2"
echo ""
echo "  For detailed instructions, see README.md"
echo ""
