#!/usr/bin/env bash
# =============================================================================
# Codika WhatsApp Connector - One-Command Setup
# =============================================================================
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}>>>${NC} $1"; }
success() { echo -e "${GREEN}>>>${NC} $1"; }
warn()    { echo -e "${YELLOW}>>>${NC} $1"; }
fail()    { echo -e "${RED}>>>${NC} $1"; exit 1; }

echo ""
echo -e "${BOLD}  Codika WhatsApp Connector Setup${NC}"
echo "  ================================="
echo ""

# ---- 1. Check Docker ----
if ! command -v docker &> /dev/null; then
    info "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    success "Docker installed"
fi

if ! docker compose version &> /dev/null 2>&1; then
    fail "Docker Compose V2 not found. Update Docker: https://docs.docker.com/compose/install/"
fi

success "Docker ready"

# ---- 2. Check if already configured ----
if [ -f .env ]; then
    warn "Already configured. Starting services..."
    docker compose up -d
    API_KEY=$(grep EVOLUTION_API_KEY .env | cut -d= -f2)
    SERVER_IP=$(grep EVOLUTION_SERVER_URL .env | sed 's|.*//||' | sed 's|:.*||')
    echo ""
    success "Services running!"
    echo ""
    echo -e "  ${BOLD}Management page:${NC}  http://${SERVER_IP}:3000#key=${API_KEY}"
    echo ""
    exit 0
fi

# ---- 3. Collect the ONE thing we need ----
echo -e "  You need ${BOLD}one thing${NC}: your Codika webhook URL."
echo "  (You got this from your Codika dashboard or support team)"
echo ""
read -p "  Webhook URL: " WEBHOOK_URL

if [ -z "$WEBHOOK_URL" ]; then
    fail "Webhook URL is required. Ask your Codika contact for it."
fi

# ---- 4. Auto-detect everything else ----
info "Detecting server IP..."

# Try multiple methods to get public IP
SERVER_IP=$(curl -s --max-time 5 https://ifconfig.me 2>/dev/null \
         || curl -s --max-time 5 https://api.ipify.org 2>/dev/null \
         || curl -s --max-time 5 https://icanhazip.com 2>/dev/null \
         || hostname -I 2>/dev/null | awk '{print $1}' \
         || echo "localhost")

success "Server IP: ${SERVER_IP}"

# Generate all secrets automatically
API_KEY=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 16)

# ---- 5. Write .env (user never touches this) ----
cat > .env << EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Do NOT edit manually. Re-run ./setup.sh to reconfigure.

WEBHOOK_URL=${WEBHOOK_URL}
WEBHOOK_ENABLED=true
EVOLUTION_API_KEY=${API_KEY}
EVOLUTION_API_VERSION=v2.3.7
EVOLUTION_API_PORT=8080
EVOLUTION_SERVER_URL=http://${SERVER_IP}:8080
SETUP_UI_PORT=3000
POSTGRES_DB=evolution_db
POSTGRES_USER=evolution
POSTGRES_PASSWORD=${DB_PASSWORD}
SESSION_PHONE_CLIENT=Community Bot
DEL_INSTANCE=false
EOF

success "Configuration generated"

# ---- 6. Start everything ----
info "Starting services (this may take a minute on first run)..."
docker compose up -d

info "Waiting for services to be ready..."
attempts=0
until docker exec evolution_api wget --spider -q http://localhost:8080 2>/dev/null; do
    attempts=$((attempts + 1))
    if [ $attempts -ge 45 ]; then
        fail "Services did not start. Run: docker compose logs"
    fi
    sleep 2
done

# ---- 7. Done! ----
echo ""
echo -e "${GREEN}  ==========================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}  ==========================================${NC}"
echo ""
echo -e "  ${BOLD}Open this URL in your browser to connect WhatsApp:${NC}"
echo ""
echo -e "  ${BLUE}http://${SERVER_IP}:3000#key=${API_KEY}${NC}"
echo ""
echo "  Then:"
echo "  1. Click 'Create Instance & Get QR Code'"
echo "  2. Open WhatsApp on your phone"
echo "  3. Go to Settings > Linked Devices > Link a Device"
echo "  4. Scan the QR code shown on the page"
echo ""
echo "  That's it! Your bot will start receiving group messages."
echo ""
echo -e "  ${YELLOW}Save this URL - you'll need it to manage your connector.${NC}"
echo ""
